version: "3"
services:
  node:
    image: andyaxie/testnet:latest
    restart: always
    hostname: node
    container_name: node
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp
    volumes:
      - ~/.skymavis/chaindata:/ethereum
    environment:
      - PASSWORD=${PASSWORD}
      - PRIVATE_KEY=${VALIDATOR_PRIVATE_KEY}
      - BOOTNODES=${BOOTNODES}
      - NETWORK_ID=${NETWORK_ID}
  chain-stats:
    image: andyaxie/chain-stats-backend:latest
    restart: always
    hostname: chain-stats
    container_name: chain-stats-backend
    depends_on:
      - node
    environment:
      - RPC_HOST=node
      - INSTANCE_NAME=${INSTANCE_NAME}
      - WS_SERVER=${CHAIN_STATS_WS_SERVER}
      - WS_SECRET=${CHAIN_STATS_WS_SECRET}
  oracle-db:
    image: postgres:latest
    restart: always
    hostname: oracle-db
    container_name: oracle-db
    ports:
      - 54321:5432
    volumes:
      - ~/.skymavis/oracledata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  oracle:
    image: andyaxie/oracle:latest
    restart: always
    hostname: oracle
    container_name: oracle
    depends_on:
      - node
      - oracle-db
    volumes:
      - ./config:/opt/config
    environment:
      - DEPLOYMENT=${DEPLOYMENT}
      - ORACLE_DATABASE__URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@oracle-db:5432/${POSTGRES_DB}
      - ORACLE_SECRET__PRIVATE_KEY=${VALIDATOR_PRIVATE_KEY}
      - ORACLE_MAINCHAIN__ENDPOINT=${ETHEREUM_ENDPOINT}
