min_kept_tasks = 1000

[mainchain]
  # An endpoint that can query ethereum data, i.e. Infura or Alchemy like
  chain_id = 1
  block_time = 15
  safe_block_confirmation = 7
  gateway_starting_block = 0
  registry = ""

# Address and block number of gateway contract on side chain
[sidechain]
  chain_id = 2020
  block_time = 3
  safe_block_confirmation = 2
  gateway_starting_block = 0
  registry = ""

[expired_time_secs]
  done_task = 2592000
  failed_task = 7776000
